[package]
name = "matrix"
version = "2026.8.13"
edition = "2021"
description = "High-performance, logic-driven dev engine and TUI"
license = "GPL-3.0-or-later"
repository = "https://github.com/ItzJoris03/matrix"
readme = "README.md"

[dependencies]
# Async runtime
tokio = { version = "1.36", features = ["full"] }

# TUI
ratatui = "0.26"
crossterm = { version = "0.27", features = ["events"] }

# System Stats
sysinfo = "0.30"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
chrono = "0.4"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
nix = { version = "0.31.2", features = ["signal"] }
arboard = "3.6.1"
uuid = { version = "1.23.0", features = ["v4"] }
regex = "1.10"
ureq = { version = "2.12", features = ["json"] }
